---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 12.0.3

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0
    driver:
      customize:
        memory: 1024
    run_list:
      - recipe[yum-epel]

suites:
  - name: default
    run_list:
      - recipe[example5::default]
    attributes: {}
